// English adapter for VetWel botanical reference data.
(()=>{
const N={"egir-otu":"Sweet Flag","civanpercemi":"Yarrow","koyun-otu":"Agrimony","dulavrat-otu":"Greater Burdock","kadintuzlugu":"Barberry","kestere-otu":"Betony","hus":"Birch","pitrak":"Bidens","brokoli-tohumu":"Broccoli Seed","aynisafa":"Calendula","coban-cantasi":"Shepherd's Purse","kizil-kantaron":"Common Centaury","papatya":"German Chamomile","kirlangic-otu":"Greater Celandine","alic":"Hawthorn","ekinezya":"Echinacea","atkuyrugu":"Horsetail","yaki-otu":"Willowherb","tekesakali":"Meadowsweet","rezene":"Fennel","yogurt-otu":"Bedstraw","yer-sarmasigi":"Ground Ivy","meyan-koku":"Licorice Root","bozagan-otu":"Cudweed","altin-otu":"Immortelle / Sandy Everlasting","serbetci-otu":"Hops","sari-kantaron":"St. John's Wort","aslan-otu":"Motherwort","lespedeza":"Lespedeza","sari-yonca":"Sweet Clover","melisa":"Lemon Balm","nane":"Mint","kedi-nanesi":"Catnip","tarla-kayiskirani":"Restharrow","oregano":"Oregano","java-cayi":"Java Tea","sakayik":"Peony","fasulye":"Common Bean","sinirli-ot":"Plantain","kus-otu":"Knotgrass","su-biberi":"Persicaria / Smartweed","mese-yapragi":"English Oak Leaf","kokboya":"Madder","adacayi":"Sage","salsola":"Salsola","cayir-dugmesi":"Great Burnet","karakafes":"Comfrey","karahindiba":"Dandelion","kekik":"Thyme","ihlamur":"Linden","kirmizi-yonca":"Red Clover","isirgan":"Nettle","kedi-otu":"Valerian","menekse":"Wild Pansy","okaliptus":"Eucalyptus","cam-yapragi":"Pine Leaf","akcaagac-yapragi":"Maple Leaf","keklik-otu":"Keklik Herb","armut-ekstresi":"Pear Extract"};
const E={"hus":["Birch Root","Birch Leaf","Silver Birch","Silver Birch Leaf"],"papatya":["Chamomile"],"menekse":["Violet"],"kedi-nanesi":["Catnip Extract"],"ekinezya":["Purple Coneflower"],"isirgan":["Stinging Nettle"],"kus-otu":["Common Knotgrass"],"su-biberi":["Lady's-Thumb / Persicaria"],"sinirli-ot":["Psyllium / Plantain"],"pitrak":["Beggar-Ticks"],"altin-otu":["Helichrysum"],"yogurt-otu":["Galium","Cleavers","Lady's Bedstraw"],"dulavrat-otu":["Burdock"],"cayir-dugmesi":["Burnet"],"meyan-koku":["Licorice"]};
const A={flower:"A flowering botanical used as a plant-derived ingredient in VetWel formulations.",leaf:"A leaf-rich or aromatic botanical used as a plant-derived ingredient in VetWel formulations.",root:"A botanical whose root or rhizome is an important plant source.",spike:"An herbaceous botanical with upright or spike-like growth structures.",shrub:"A shrub- or tree-derived botanical ingredient."};
const role=(products=[])=>{const p=products.join(" "),areas=[];if(/KidneyWel|Cleanse/.test(p))areas.push("renal and urinary wellness");if(/LiverWel/.test(p))areas.push("hepatic and digestive wellness");if(/SkinWel/.test(p))areas.push("skin and coat wellness");if(/HeartWel/.test(p))areas.push("cardiovascular wellness");if(/CalmWel/.test(p))areas.push("calm behavior and environmental adaptation");if(/LactoWel/.test(p))areas.push("digestive, microbiota and gut wellness");if(/DentaWel/.test(p))areas.push("oral and gum care");if(/Breathe Ease/.test(p))areas.push("respiratory wellness");if(/Malt Paste/.test(p))areas.push("digestive and hairball-care support");if(/Malign Detox/.test(p))areas.push("specialized multi-botanical nutritional support");const unique=[...new Set(areas)];return unique.length?`Included as part of VetWel’s multi-botanical approach to ${unique.join(", ")}.`:"Included as part of VetWel’s multi-botanical formulation approach.";};
const base=window.VETWEL_BOTANICALS||[];
window.VETWEL_BOTANICALS_EN=base.map(p=>({...p,name:N[p.id]||p.name,latin:p.id==="keklik-otu"?"Species not specified on the product page":p.latin,aliases:[...(p.aliases||[]),...(E[p.id]||[])],about:A[p.visual]||A.leaf,role:role(p.products),caution:p.id==="sari-kantaron"?"St. John's Wort may have interaction potential with some medications; animals receiving regular medication should be evaluated by a veterinarian.":undefined}));
window.VetWelBotanicalEN={normalize(v){return String(v||"").toLocaleLowerCase("en-US").replace(/^\s*\d+\.\s*/,"").replace(/[®™]/g,"").replace(/\s+/g," ").trim();},find(fullText,labelText){const full=String(fullText||"").toLocaleLowerCase("en-US"),label=this.normalize(labelText);return window.VETWEL_BOTANICALS_EN.find(p=>{const latin=String(p.latin||"").toLocaleLowerCase("en-US");if(latin&&!latin.includes("not specified")){const parts=latin.split("/").map(x=>x.trim().replace(/\s+l\.$/,"")).filter(Boolean);if(parts.some(part=>full.includes(part)))return true;}return [p.name,p.latin,...(p.aliases||[])].map(x=>this.normalize(x)).includes(label);});},visual(type="leaf"){return window.VetWelBotanical.visual(type);}};
})();

// Real-photo correction for the English Botanical Guide and English product modals.
(()=>{if(document.querySelector('script[data-vetwel-en-photo-fix]'))return;const s=document.createElement('script');s.src='botanical-photo-fix.js';s.defer=true;s.dataset.vetwelEnPhotoFix='1';s.onerror=()=>console.warn('VetWel English botanical photo fix could not be loaded.');document.head.appendChild(s)})();
