window.VETWEL_CLINICS = [
  {name:"Vetumay Veteriner Muayenehanesi",city:"İstanbul",district:"Ümraniye",address:"İstiklal Mah. Kavaklıdere Cad. No:110/A",phone:"05073104325"},
  {name:"Duru Veteriner Kliniği",city:"Bursa",district:"Orhangazi",address:"Hürriyet Mah. Tozkoparan Cad. No:92/B",phone:"05308324427"},
  {name:"İstanimal Veterinerlik Hizmetleri",city:"İstanbul",district:"Pendik",address:"Bahçelievler Mah. Adnan Menderes Bulv. İsmen Apt. No:7/A",phone:"05056101223"},
  {name:"Veteran Veteriner Hizmetleri",city:"İstanbul",district:"Bağcılar",address:"Merkez Mah. Güngören Cad. B Blok No:20-22A",phone:"05308718797"},
  {name:"Vetistan Veteriner Kliniği",city:"İstanbul",district:"Beylikdüzü",address:"Barış Mah. Gazi Yüzbaşı Turgay Salih Canoğlu Sk. Kadelen Apt. A Blok No:2/1",phone:"05317667657"},
  {name:"Carnivet Veteriner Muayene",city:"İstanbul",district:"Küçükçekmece",address:"İstasyon Mah. 1. Yeni Cami Sk. No:1/3",phone:"05330480008"},
  {name:"YEK Veteriner Sağlık Hizmetleri",city:"Kocaeli",district:"Gebze",address:"Mevlana Mah. Issıkgöl Cad. No:99/7",phone:"05324910124"},
  {name:"Woof Veteriner Kliniği",city:"İstanbul",district:"Çekmeköy",address:"Alemdağ Mah. Reşadiye Cad. No:17/A",phone:"05077735864"},
  {name:"Asil Veteriner Kliniği",city:"İstanbul",district:"Ümraniye",address:"İstiklal Mah. Mithatpaşa Cad. No:46/A",phone:"05465567058"},
  {name:"Kent Veteriner Kliniği",city:"İstanbul",district:"Eyüpsultan",address:"5. Levent Mah. Fatih Sultan Mehmet Bulv. No:4/5AB",phone:"05010305368"},
  {name:"Sevcan Veteriner Kliniği",city:"İstanbul",district:"Kadıköy",address:"Merdivenköy Mah. Fahrettin Kerim Gökay Cad. No:223/B",phone:"05303870294"},
  {name:"Aliss Veteriner Kliniği",city:"İstanbul",district:"Çekmeköy",address:"Güngören Mah. Yazgı Sk. No:5/A",phone:"05334609700"},
  {name:"Pet Klinik Veteriner Kliniği",city:"Bursa",district:"Osmangazi",address:"Çekirge Cad. Manolya Apt. No:46/1",phone:"02242333540"},
  {name:"Bilmav Veteriner Kliniği",city:"İstanbul",district:"Kartal",address:"Yakacık Çarşı Mah. Kartal Cad. Ahmet Dayı İş Hanı No:20/E",phone:"05317808309"},
  {name:"Bölge Veteriner Kliniği",city:"İstanbul",district:"Kadıköy",address:"Bostancı Mah. Şemsettin Günaltay Cad. Kervan Apt. No:26A",phone:"05013541438"},
  {name:"Viapet Veteriner Kliniği",city:"İstanbul",district:"Pendik",address:"Harmandere Mah. Reyhan Cad. Evra Life A Blok No:65/AA",phone:""},
  {name:"Vetix Veteriner Kliniği",city:"İstanbul",district:"Ümraniye",address:"Şerifali Mah. Turgut Özal Bulv. No:109/B",phone:"02165945644"},
  {name:"Medzoa Veteriner Kliniği",city:"İstanbul",district:"Kadıköy",address:"Kozyatağı Mah. Kocayol Cad. M. Yeşim Apt. No:9B",phone:"05320645520"},
  {name:"Dr Vets Veteriner Kliniği",city:"İstanbul",district:"Avcılar",address:"Tahtakale Mah. Ispartakule Bulv. Ebruli Ispartakule C2 Blok No:16/1G",phone:"05433363419"},
  {name:"Seyrantepe Veteriner",city:"İstanbul",district:"Kağıthane",address:"Seyrantepe Mah. İbrahim Karaoğlanoğlu Cad. No:175/B",phone:"05469309043"},
  {name:"Vetmedi Veteriner Tanı ve Tedavi Merkezi",city:"İstanbul",district:"Kadıköy",address:"Zühtüpaşa Mah. Zahit Bey Sk. No:8",phone:"05541557575"},
  {name:"Vet Akdeniz Veteriner Kliniği",city:"İstanbul",district:"Kadıköy",address:"Fenerbahçe Mah. Hacı Mehmet Efendi Sk. No:9/F",phone:"02164674743"},
  {name:"Merdivenköy Veteriner Muayenehanesi",city:"İstanbul",district:"Kadıköy",address:"Merdivenköy Mah. Hızır Reis Sk. No:4/B",phone:"05522263691"},
  {name:"Özel Pendik Veteriner",city:"İstanbul",district:"Pendik",address:"Doğu Mah. Aydınlı Yolu Cad. Alibey Evleri No:53/A",phone:"05543491501"},
  {name:"Çengelköy Veteriner Kliniği",city:"İstanbul",district:"Üsküdar",address:"Güzeltepe Mah. Sahra Sk. No:4",phone:"05516280740"},
  {name:"ŞirinPati Veteriner Hizmetleri",city:"İstanbul",district:"Bağcılar",address:"Göztepe Mah. Bosna Cad. No:10-14/G",phone:"05334422050"},
  {name:"Ekol Veteriner Kliniği",city:"İstanbul",district:"Tuzla",address:"Postane Mah. Tahaffuzhane Cad. No:44B",phone:"05517113565"},
  {name:"Siyendi Veteriner Kliniği",city:"İstanbul",district:"Kartal",address:"Karlıtepe Mah. Yaşar Doğu Cad. No:33/A",phone:"05011618181"},
  {name:"Vinka Veterinerlik Hizmetleri",city:"İstanbul",district:"Çekmeköy",address:"Hamidiye Mah. Özmen Sk. Dostlar Apt. No:1A",phone:"05306490838"},
  {name:"Luna Veteriner Kliniği",city:"Kocaeli",district:"Gebze",address:"Hacıhalil Mah. 1229/2 Sok. No:9B",phone:"05332315862"},
  {name:"Jasmin Veterinerlik Hizmetleri",city:"İstanbul",district:"Pendik",address:"Kurtköy Mah. Seyin Onbaşı Sk. No:29/A",phone:"05425919994"},
  {name:"Çare Veteriner Kliniği",city:"İstanbul",district:"Tuzla",address:"Aydınlı Mah. Mayıs Sok. Dumankaya Adres Lobi A1/A2 Blok No:2A1+A2/203",phone:"05388257204"},
  {name:"Vetidea Veteriner Kliniği",city:"İstanbul",district:"Kadıköy",address:"Şair Arşi Cad. No:10/A, Merdivenköy",phone:"02167710594"},
  {name:"İlkadım Veteriner Hizmetleri",city:"İstanbul",district:"Kadıköy",address:"19 Mayıs Mah. Şahin Sk. Özgen Apt. No:10/1",phone:"02169096004"},
  {name:"Sarıca Veteriner Muayenehanesi",city:"İstanbul",district:"Ümraniye",address:"Namık Kemal Mah. Aykut Sok. No:32A",phone:"05357969251"},
  {name:"Pati İzi Veterinerlik",city:"İstanbul",district:"Tuzla",address:"Postane Mah. Barbaros Hayrettin Cad. No:27/A",phone:"05526008990"},
  {name:"Beylerbeyi Veteriner Kliniği",city:"İstanbul",district:"Üsküdar",address:"Beylerbeyi Mah. Abdullah Ağa Cad. No:4/9",phone:"05357761466"},
  {name:"Köri Veteriner Poliklinik Hizmetleri",city:"İstanbul",district:"Tuzla",address:"Postane Mah. Manastır Yolu Cad. No:68/S9",phone:""},
  {name:"Galaksi Veteriner Muayenehanesi",city:"İstanbul",district:"Kadıköy",address:"Bostancı Mah. Menekşe Sok. Akabe Apt. No:13/A",phone:"05411707555"},
  {name:"Vetwise Veteriner Kliniği",city:"İstanbul",district:"Kadıköy",address:"Erenköy Mah. Nurettin Ali Berkol Sok. No:13-15B",phone:"05367989473"},
  {name:"Ege Veteriner Muayenehanesi",city:"İstanbul",district:"Tuzla",address:"Aydıntepe Mah. Marmara Cad. No:9/1",phone:"05557125914"},
  {name:"Mokii Veteriner",city:"İstanbul",district:"Pendik",address:"Kaynarca Mah. Hastane Cad. Kanca Apt. No:20/A",phone:"05417307534"},
  {name:"Orient Veteriner Kliniği",city:"İstanbul",district:"Üsküdar",address:"Bahçelievler Mah. Ayça Sok. No:13/A",phone:"05465538976"},
  {name:"Mr.Vet Veteriner Muayenehanesi",city:"İstanbul",district:"Ümraniye",address:"Şehit Ünal Kalafat Cad. Madenler Sok. No:3-A",phone:"02163148630"},
  {name:"Tuzla Veteriner Kliniği",city:"İstanbul",district:"Tuzla",address:"Evliya Çelebi Mah. Hatboyu Cad. No:48/A",phone:"05323892802"},
  {name:"Pati Tepe Veteriner Kliniği",city:"İstanbul",district:"Maltepe",address:"Zümrütevler Mah. Firuzan Sok. No:7/D",phone:"05070087969"},
  {name:"Dragos Veteriner Kliniği",city:"İstanbul",district:"Kartal",address:"Orhantepe Mah. Orhangazi Cad. No:1/A",phone:"05353009914"},
  {name:"Lumos Veterinerlik Hizmetleri",city:"İstanbul",district:"Maltepe",address:"Altayçeşme Mah. Gazipaşa Sk. No:1/C",phone:"05317858754"},
  {name:"Kriton Pati Veteriner Kliniği",city:"İstanbul",district:"Kadıköy",address:"19 Mayıs Mah. Okur Sk. STFA B5 No:17/C",phone:"05439525494"},
  {name:"Nişantepe Veteriner Kliniği",city:"İstanbul",district:"Çekmeköy",address:"Nişantepe Mah. Gelin Çiçeği Sk. Alemdağ TOKİ Emlak Konutları A9 No:5-12/2",phone:"05336858566"},
  {name:"Abbavet Veteriner Kliniği",city:"İstanbul",district:"Ümraniye",address:"Necip Fazıl Mah. Yılmaz Sk. No:3/A",phone:"05424573091"},
  {name:"Defne Dilara Veteriner Kliniği",city:"İstanbul",district:"Maltepe",address:"Barlarbaşı Mah. Şahin Sk. No:39/A",phone:"05528315232"},
  {name:"Major Veteriner Kliniği",city:"İstanbul",district:"Kadıköy",address:"Merdivenköy Mah. Melih Cevdet Anday Sk. No:25/A",phone:"05013454189"},
  {name:"Vetümraniye Veteriner Kliniği",city:"İstanbul",district:"Ümraniye",address:"İstiklal Mah. Mithatpaşa Cad. No:48/C",phone:"05333364552"},
  {name:"Animal Planet Veteriner Kliniği",city:"Kocaeli",district:"Darıca",address:"Bayramoğlu Mah. F. Sultan Mehmet Cad. No:150",phone:"05325207069"},
  {name:"Vet34 Veteriner Kliniği",city:"İstanbul",district:"Kartal",address:"Orhantepe Mah. Üsküdar Cad. No:192H",phone:"05330460838"},
  {name:"Puppy Veteriner Kliniği",city:"İstanbul",district:"Maltepe",address:"Altıntepe Mah. İlkbahar Çıkmazı Sk. No:3/A",phone:"05435333395"},
  {name:"Arterium Veteriner Klinik Hizmetleri",city:"İstanbul",district:"Başakşehir",address:"Başakşehir Mah. Toros Cad. Arterium AVC. No:1R",phone:"05335565423"},
  {name:"Mostar Veteriner Hizmetleri",city:"İstanbul",district:"Pendik",address:"Bahçelievler Mah. Mostar Bulv. No:26/A",phone:"05335546034"},
  {name:"Alya Veteriner Hizmetleri",city:"İstanbul",district:"Bağcılar",address:"İnönü Mah. Hoca Ahmet Yesevi Cd. No:15/B",phone:"05423085669"},
  {name:"Patikule Veteriner Hizmetleri",city:"İstanbul",district:"Avcılar",address:"Tahtakale Mah. Abdi İpekçi Cad. Avrupa Konutları Ispartakule 5 C Blok No:13/1C",phone:"05012002125"},
  {name:"Barbaros Veteriner Kliniği",city:"İstanbul",district:"Ataşehir",address:"Barbaros Mah. Mor Sümbül Sk. Nida Kule No:7/3G",phone:"05324498808"},
  {name:"Vetorka Veteriner Kliniği",city:"Bursa",district:"Nilüfer",address:"Konak Mah. Deniz Yıldızı Sk. No:2A",phone:"05332336752"},
  {name:"Eyüpsultan Veteriner",city:"İstanbul",district:"Eyüpsultan",address:"Alibeyköy Mah. Atatürk Cad. No:18/1",phone:"05337654404"},
  {name:"Güzelyalı Veteriner Kliniği",city:"Bursa",district:"Mudanya",address:"Güzelyalı Yalı Mah. Atatürk Cad. İşsun Sitesi B Blok No:62/B",phone:"05511662956"},
  {name:"Akça Veteriner Kliniği",city:"İstanbul",district:"Ümraniye",address:"Atakent Mah. Reşitpaşa Cad. No:73/C",phone:"05308811282"},
  {name:"Atalay Veteriner Kliniği",city:"İstanbul",district:"Kadıköy",address:"Kazasker 19 Mayıs Mah. Sinan Ercan Cad. No:6/1",phone:"05367891121"},
  {name:"Patişehir Veteriner Hizmetleri",city:"İstanbul",district:"Başakşehir",address:"Başak Mah. Yunus Emre Cad. No:18/1I",phone:"05528803030"},
  {name:"İlke Vet Veteriner Kliniği",city:"Bursa",district:"Mudanya",address:"Ömerbey Mah. İpar Cad. Can İş Merk. No:73/B",phone:"05301425412"},
  {name:"Mir-Vet Veteriner",city:"İstanbul",district:"Beylikdüzü",address:"Marmara Mah. Yurt Cad. No:20/1 Dük. No:29",phone:"05326699838"},
  {name:"Vet23 Veteriner Kliniği",city:"İstanbul",district:"Ümraniye",address:"Mehmet Akif Mah. Tezcan Cad. Ihlamur Apt. No:5C",phone:"05425620323"},
  {name:"Florya Veteriner Kliniği",city:"İstanbul",district:"Küçükçekmece",address:"Şenlikköy Efeker Sokak No:10",phone:"02126631387"},
  {name:"Mavi Veteriner Kliniği",city:"İstanbul",district:"Kadıköy",address:"Topağaç Sk. Caddebostan Mah. Bağdat Cad. Marmara Apt. No:248 16/B",phone:"02167841808"},
  {name:"Vetscience Veteriner Kliniği",city:"İstanbul",district:"Başakşehir",address:"Bahçeşehir 1. Kısım Mah. Vali Recep Yazıcıoğlu Cad. No:64 İç Kapı No:34",phone:"05337010242"}
];
